version: '3.8'
services:
  1password_logs:
    image: hasecuritysolutions/1password_api:2.4.0
    volumes:
      - /opt/elastic_stack/ca/ca.crt:/etc/beats/ca.crt:ro
      - /opt/elastic_stack/beats/beats1.crt:/etc/beats/beats.crt:ro
      - /opt/elastic_stack/beats/beats1.key:/etc/beats/beats.key:ro
      - /opt/elastic_stack/beats/eventsapibeat:/opt/eventsapibeat
    networks:
      - customer100
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.hostname == somehost]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  customer100:
    driver: overlay
    attachable: true
